Controllers/FaultController.cs
using Castle.Core.Resource;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NuGet.Protocol.Plugins;
using teknik_servis.WebApp.Models;
using teknikServisMVC.Models.Entities.Concrete;
using teknikServisMVC.Repositories;

namespace teknikServisMVC.Controllers
{
    public class FaultController : Controller
    {
        readonly ArizaRepository repository;
        readonly MusteriRepository musteriRepository;
        private Ariza ariza = new Ariza();

        public FaultController(ArizaRepository repository , MusteriRepository musteriRepository)
        {
            this.repository = repository;
            this.musteriRepository = musteriRepository;
        }
        [HttpGet]
        public IActionResult AllFaults()
        {
            ICollection<Ariza> arizalar = repository.GetAll().ToList();
            return View(Tuple.Create<object, List<object>, string>(new Ariza(), arizalar.Cast<object>().ToList(), "table table-hover js-exportable"));
        }
        [HttpGet]
        public IActionResult FinalizedFaults()
        {
            ICollection<Ariza> arizalar = repository.GetAllFinalized();
            return View(Tuple.Create<object, List<object>, string>(ariza, arizalar.Cast<object>().ToList(), "table table-hover js-exportable"));
        }
        [HttpGet]
        public IActionResult ProcessFaults()
        {
            ICollection<Ariza> arizalar = repository.GetAllInProgress();
            return View(Tuple.Create<object, List<object>, string>(ariza, arizalar.Cast<object>().ToList(), "table table-hover js-exportable"));
        }
        [HttpGet]
        public IActionResult NewFault()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> NewFault([FromForm] NewFaultModel faultModel)
        {

            Musteri customer = await musteriRepository.GetByEmail(faultModel.Eposta);

            if (customer != null)
            {
                Ariza fault = new Ariza()
                {
                    Aciklama = faultModel.Aciklama,
                    Cihaz = new Cihaz()
                    {
                        Marka = faultModel.Marka,
                        Model = faultModel.Model,
                        SeriNumarasi = faultModel.SeriNumarasi,
                    },
                    MusteriId = customer.Id,
                    Musteri = customer,
                    ArizaDurumuId = 1,
                    ArizaTakipNumarasi = faultModel.ArizaTakipNumarasi,
                };

                var result = await repository.AddAsync(fault);

                if (result)
                {
                    await repository.SaveAsync();
                    return RedirectToAction("AllFaults");
                }
                else
                {
                    return StatusCode(500);
                }
                
            }

            return StatusCode(500);
        }
        [HttpGet]
        public IActionResult LastFaults()
        {
            return PartialView();
        }
        [HttpGet]
        public IActionResult LastUpdates()
        {
            return PartialView();
        }

        [HttpPost]
        public IActionResult FaultStatus(string ArizaTakipNumarasi)
        {
            Ariza arıza = repository.GetFaultbyTN(ArizaTakipNumarasi);
            if (arıza.Status == true)
                return View(arıza);
            else
                return RedirectToAction("Index", "Home");
        }
        public async Task<IActionResult> StatusUpdate(int id)
        {
            var updatestatusmodel = await repository.GetByIdAsync(id);
            updatestatusmodel.ArizaDurumuId = updatestatusmodel.ArizaDurumuId + 1;

            var result = repository.Update(updatestatusmodel);

            if (result)
            {
                await musteriRepository.SaveAsync();
                return RedirectToAction("AllFaults", "Fault");
            }
            else
                return StatusCode(500);
        }

        public async Task<IActionResult> StatusChange(int id)
        {
            var model = await repository.GetByIdAsync(id);
            model.Status = model.Status ? false : true;
            
            var result = repository.Update(model);

            if (result)
            {
                await musteriRepository.SaveAsync();
                return RedirectToAction("AllFaults", "Fault");
            }
            else
                return StatusCode(500);
        }
    }
}

Controllers/FaultStatusController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using teknikServisMVC.Models.Entities.Concrete;
using teknikServisMVC.Repositories;

namespace teknikServisMVC.Controllers
{
    public class FaultStatusController : Controller
    {
        readonly ArizaDurumuRepository repository;

        public FaultStatusController(ArizaDurumuRepository arizaDurumuRepository)
        {
            repository = arizaDurumuRepository;
        }
        [HttpGet]
        public IActionResult CreateFaultStatus()
        {
            ICollection<ArizaDurumu> arizaDurumları = repository.GetAll().ToList();
            return View(arizaDurumları);
        }
        [HttpPost]
        public async Task<IActionResult> CreateFaultStatus(ArizaDurumu model)
        {
            bool result = await repository.AddAsync(model);
            if (result)
            {
                await repository.SaveAsync();
                return RedirectToAction("CreateFaultStatus");
            }
               
            return StatusCode(500);
        }
    }
}

ViewComponents/DynamicTableViewComponent.cs
using Microsoft.AspNetCore.Mvc;


namespace teknikServisMVC.ViewComponents
{
    public class DynamicTableViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(Tuple<object, List<object>, string> tuple)
        {
            return View(tuple);
        }
    }
    public class TableHeader
    {
        //Entity class names are converted to Turkish.
        public static string[] entity_names = new string[] { "Adres", "Cihaz", "İletişim", "Müşteri", "Arıza" };

        //property names are converted to Turkish.
        public static string[] Fault = { "Açıklama", "Cihaz", "Müşteri", "Takip No", "Oluşturulma Tarihi", "Güncellenme Tarihi", "Durumu" };
        public static string[] Address = { "Ülke", "Şehir", "Sokak/Cadde", "Posta Kodu", "Müşteri", "Oluşturulma Tarihi", "Güncellenme Tarihi", "Durumu" };
        public static string[] Contact = { "Numara", "E-posta", "Müşteri", "Oluşturulma Tarihi", "Güncellenme Tarihi", "Durumu" };
        public static string[] Customer = { "Ad", "Soyad", "Adres", "İletişim", "Oluşturulma Tarihi", "Güncellenme Tarihi", "Durumu" };
        public static string[] Device = { "Marka", "Model", "Seri Numarası", "Arıza", "Oluşturulma Tarihi", "Güncellenme Tarihi", "Durumu" };
        public static string[] FaultStatus = { "Ad", "Oluşturulma Tarihi", "Güncellenme Tarihi", "Durumu" };

        public static string UrlId(string name)
        {
            switch (name)
            {
                case "Ariza":
                    return "Fault";
                case "Adres":
                    return "Address";
                case "Iletisim":
                    return "Contact";
                case "Musteri":
                    return "Customer";
                case "Cihaz":
                    return "Device";
                case "ArizaDurumu":
                    return "FaultStatus";
                default:
                    // Belirtilen isimle eşleşen bir dizi yoksa, boş bir dizi döndürün veya isteğinize göre başka bir işlem yapın.
                    return null;
            }
        }


        public static string[] Get(string name)
        {
            switch (name)
            {
                case "Ariza":
                    return Fault;
                case "Adres":
                    return Address;
                case "Iletisim":
                    return Contact;
                case "Musteri":
                    return Customer;
                case "Cihaz":
                    return Device;
                case "ArizaDurumu":
                    return FaultStatus;
                default:
                    // Belirtilen isimle eşleşen bir dizi yoksa, boş bir dizi döndürün veya isteğinize göre başka bir işlem yapın.
                    return new string[0];
            }
        }
    }
}

Views/Fault/AllFaults.cshtml
@{
    ViewData["Title"] = "Tüm Arıza Kayıtları";
    Layout = "~/Views/Shared/PanelLayout.cshtml";
}
@model Tuple<object,List<object>,string>

<section class="content">

    <div class="body_scroll">
        <div class="block-header">
            <div class="row">
                <div class="col-lg-7 col-md-6 col-sm-12">
                    <h2>Tüm Arıza Kayıtları</h2>

                    <button class="btn btn-primary btn-icon mobile_menu" type="button">
                        <i class="zmdi zmdi-sort-amount-desc"></i>
                    </button>
                </div>
                <div class="col-lg-5 col-md-6 col-sm-12">
                    <button class="btn btn-primary btn-icon float-right right_icon_toggle_btn" type="button">
                        <i class="zmdi zmdi-arrow-right"></i>
                    </button>
                </div>
                <div class="col-sm-4 mb-4">
                    <div class="row">
                        <div class="col-sm-8">
                            <select class="form-control show-tick ms select2" id="arizaDurumFilter" name="RoleName" style="background-color:white!important" data-placeholder="Arıza Durumu Filtresi">
                                <option></option>
                                <option value="islemde">İşlemdeki Arıza Kayıtları</option>
                                <option value="sonuclanmis">Sonuçlanmış Arıza Kayıtları</option>
                            </select>
                        </div>
                        <div class="col-sm-4">
                            <button style="height:38px;margin-top:-0.5px" onclick="Filtrele();" type="submit" class="btn btn-md btn-warning">Filtrele</button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="container-fluid">
                <div class="row clearfix">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="body">
                                <div class="table-responsive">
                                    @await Component.InvokeAsync("DynamicTable",Model)
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- Jquery DataTable Plugin Js -->
<script src="~/assets/panel/bundles/datatablescripts.bundle.js"></script>
<script src="~/assets/panel/plugins/jquery-datatable/buttons/buttons.bootstrap4.min.js"></script>
<script src="~/assets/panel/js/pages/tables/jquery-datatable.js"></script>

<script src="~/assets/panel/plugins/jquery-inputmask/jquery.inputmask.bundle.js"></script> <!-- Input Mask Plugin Js -->
<script src="~/assets/panel/plugins/select2/select2.min.js"></script> <!-- Select2 Js -->
<script src="~/assets/panel/plugins/bootstrap-colorpicker/js/bootstrap-colorpicker.js"></script>
<script src="~/assets/panel/js/pages/forms/advanced-form-elements.js"></script>
<script>
    function Filtrele() {
        let filter = $('#arizaDurumFilter').val();

        if (filter == "sonuclanmis") {
            window.location.href = "/Fault/FinalizedFaults/";
        }
        if (filter == "islemde") {
            window.location.href = "/Fault/ProcessFaults/";
        }
    }
</script>

Views/Fault/FaultStatus.cshtml
@using teknikServisMVC.Models.Entities.Concrete;

@{
    Layout = null;
}

@model Ariza;

<!DOCTYPE html>
<html lang="en">


<!-- blank-page14-->

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Teknik servis uygulaması Selçuk Üniversitesi Teknoloji Fakültesi">
    <meta name="author" content="Shreethemes">

    <link rel="shortcut icon" href="images/favicon.ico">

    <title>Teknik Servis - Arıza Sorgu</title>

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,500,600,700|Poppins" rel="stylesheet">
    <!-- Bootstrap core CSS -->
    <link href="~/assets/user/css/bootstrap.min.css" rel="stylesheet">

    <!-- Magnificpopup Css -->
    <link rel="stylesheet" type="text/css" href="~/assets/user/css/magnific-popup.css">

    <!-- Bootstrap core CSS -->
    <link href="~/assets/user/css/materialdesignicons.min.css" rel="stylesheet">
    <link href="~/assets/user/css/fontawesome.css" rel="stylesheet">
    <link href="~/assets/user/css/pe-icon-7-stroke.css" rel="stylesheet">

    <!--Slider-->
    <link rel="stylesheet" href="~/assets/user/css/slick.css" />
    <link rel="stylesheet" href="~/assets/user/css/slick-theme.css" />

    <!-- Custom styles for this template -->
    <link href="~/assets/user/css/style.css" rel="stylesheet">
    <link href="~/assets/user/css/menu.css" rel="stylesheet">
    <link href="~/assets/user/css/default.css" rel="stylesheet">

</head>

<body>
    <!-- Loader -->
    <div id="preloader">
        <div id="status">
            <div class="spinner">
                <div class="double-bounce1"></div>
                <div class="double-bounce2"></div>
            </div>
        </div>
    </div>


   
    <!-- End Navigation Bar-->
    <!-- HOME START-->
    <section class="bg-half" style="background-image: url('/assets/user/images/home/bg-pages.jpg');padding-top:100px;padding-bottom:100px;">
        <div class="home-center">
            <div class="home-desc">
                <div class="container">
                    <div style="margin-bottom: 30px;" class="row">
                        <div style="display:flex;" class="col-md-6">
                            <div style="inline-size:-webkit-fill-available;" class="bg-white p-30 rounded box-shadow">
                                <h5 class="form-title mb-4 text-center font-weight-bold">Sorgu Sonucu</h5>

                                <div>
                                    <label for="sorguNo">Sorgu Numarası</label>
                                    <input disabled name="sorguNo" class="form-control" type="text" value="@Model.ArizaTakipNumarasi">
                                    <br>
                                    <label for="sorguDurum">Sorgu Durumu</label>
                                    <input disabled name="sorguDurum" class="form-control" type="text" value="@Model.ArizaDurumu.Ad">
                                    <br>
                                    <label for="sorguDesc">Açıklama</label>
                                    <textarea disabled style="resize:none;height: 100px;" name="sorguDesc" rows="3" class="form-control">@Model.Aciklama</textarea>
                                </div>
                            </div>
                        </div>
                        <div style="display:flex;" class="col-md-6">
                            <div style="inline-size:-webkit-fill-available;" class="bg-white p-30 rounded box-shadow">
                                <h5 class="form-title mb-4 text-center font-weight-bold">Müşteri Bilgileri</h5>
                                <div>
                                    <label for="NameSurname">Ad Soyad</label>
                                    <input disabled name="NameSurname" class="form-control" type="text" value="@Model.Musteri.Ad @Model.Musteri.Soyad">
                                    <br>
                                    <label for="Phone">Telefon Numarası</label>
                                    <input disabled name="Phone" class="form-control" type="text" value="@Model.Musteri.Iletisim.TelefonNumarasi">
                                    <br>
                                    <label for="Email">E-posta</label>
                                    <input disabled name="Email" class="form-control" type="text" value="@Model.Musteri.Iletisim.Eposta">
                                    <br>
                                    <label for="Address">Adres</label>
                                    <textarea disabled style="resize:none;height: 100px;" name="Address" class="form-control">@Model.Musteri.Adres.CaddeAdres @Model.Musteri.Adres.Sehir/@Model.Musteri.Adres.Ulke</textarea>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div style="display:flex;" class="col-md-6">
                            <div style="inline-size:-webkit-fill-available;" class="bg-white p-30 rounded box-shadow">
                                <h5 class="form-title mb-4 text-center font-weight-bold">Servis Durumu</h5>

                                <div>
                                    <label for="deliveryTime">Tahmini Teslim Süresi</label>
                                    <input disabled value="Mevcut Değil" name="deliveryTime" id="name" class="form-control" type="text">
                                    <br>
                                    <label for="cargoDate">Kargoya Verilme Tarihi</label>
                                    <input disabled value="Mevcut Değil" name="cargoDate" id="name" class="form-control" type="text">
                                    <br>
                                    <label for="CargoComp">Kargo Şirketi</label>
                                    <input disabled value="Mevcut Değil" name="CargoComp" id="name" class="form-control" type="text">
                                    <br>
                                    <label for="trackingNo">Takip Numarası</label>
                                    <input disabled name="trackingNo" value="@Model.ArizaTakipNumarasi" id="name" class="form-control" type="text">
                                </div>
                            </div>
                        </div>
                        <div style="display:flex;" class="col-md-6">
                            <div style="inline-size:-webkit-fill-available;" class="bg-white p-30 rounded box-shadow">
                                <h5 class="form-title mb-4 text-center font-weight-bold">Cihaz Bilgileri</h5>

                                <div>
                                    <label for="Brand">Marka</label>
                                    <input disabled name="Brand" value="@Model.Cihaz.Marka" id="name" class="form-control" type="text">
                                    <br>
                                    <label for="Model">Model</label>
                                    <input disabled name="Model" value="@Model.Cihaz.Model" id="name" class="form-control" type="text">
                                    <br>
                                    <label for="serialNumber">Seri Numarası</label>
                                    <input disabled name="serialNumber" value="@Model.Cihaz.SeriNumarasi" id="name" class="form-control" type="text">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div style="margin-top:3%;text-align: -webkit-center;" class="container">
                    <div style="text-align:center"><h2 style="z-index: 9999;color:white"><b>CİHAZ GÖRÜNTÜLERİ</b></h2></div>
                    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel" style="width:60%;">
                        <ol class="carousel-indicators">
                            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                        </ol>
                        <div class="carousel-inner">
                            <div class="carousel-item active">
                                <img class="d-block w-100" src="https://productimages.hepsiburada.net/s/484/1500/110000528997649.jpg" alt="First slide">
                            </div>
                            <div class="carousel-item">
                                <img class="d-block w-100" src="https://productimages.hepsiburada.net/s/477/500/110000519908000.jpg" alt="Second slide">
                            </div>
                            <div class="carousel-item">
                                <img class="d-block w-100" src="https://productimages.hepsiburada.net/s/477/500/110000519908001.jpg" alt="Third slide">
                            </div>
                        </div>
                        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                        </a>
                        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- HOME END-->

    <!-- Back to top -->
    <a href="#" class="back-to-top" id="back-to-top">
        <i class="mdi mdi-chevron-up"> </i>
    </a>
    <!-- Back to top -->
    <!-- js placed at the end of the document so the pages load faster -->
    <script src="~/assets/user/js/jquery.min.js"></script>
    <script src="~/assets/user/js/popper.min.js"></script>
    <script src="~/assets/user/js/bootstrap.min.js"></script>
    <!-- Portfolio -->
    <script src="~/assets/user/js/jquery.magnific-popup.min.js"></script>
    <script src="~/assets/user/js/isotope.js"></script>
    <!-- Carousel -->
    <script src="~/assets/user/js/slick.min.js"></script>
    <script src="~/assets/user/js/slick.init.js"></script>
    <!--custom script-->
    <script src="~/assets/user/js/app.js"></script>

</body>


<!-- blank-page14-->
</html>

Views/Fault/FinalizedFaults.cshtml
@{
    ViewData["Title"] = "Sonuçlanmış Arıza Kayıtları";
    Layout = "~/Views/Shared/PanelLayout.cshtml";
}
@model Tuple<object,List<object>,string>
<link rel="stylesheet" href="~/assets/panel/plugins/jquery-datatable/dataTables.bootstrap4.min.css">

<section class="content">
    <div class="body_scroll">
        <div class="block-header">
            <div class="row">
                <div class="col-lg-7 col-md-6 col-sm-12">
                    <h2>Sonuçlanmış Arıza Kayıtları</h2>

                    <button class="btn btn-primary btn-icon mobile_menu" type="button">
                        <i class="zmdi zmdi-sort-amount-desc"></i>
                    </button>
                </div>
                <div class="col-lg-5 col-md-6 col-sm-12">
                    <button class="btn btn-primary btn-icon float-right right_icon_toggle_btn" type="button">
                        <i class="zmdi zmdi-arrow-right"></i>
                    </button>
                </div>
            </div>
        </div>
        <div class="container-fluid">
            <div class="row clearfix">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="body">
                            <div class="table-responsive">
                                @await Component.InvokeAsync("DynamicTable",Model)
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- Jquery DataTable Plugin Js -->
<script src="~/assets/panel/bundles/datatablescripts.bundle.js"></script>
<script src="~/assets/panel/plugins/jquery-datatable/buttons/buttons.bootstrap4.min.js"></script>
<script src="~/assets/panel/plugins/jquery-datatable/buttons/buttons.colVis.min.js"></script>
<script src="~/assets/panel/plugins/jquery-datatable/buttons/buttons.flash.min.js"></script>
<script src="~/assets/panel/plugins/jquery-datatable/buttons/buttons.html5.min.js"></script>
<script src="~/assets/panel/plugins/jquery-datatable/buttons/buttons.print.min.js"></script>
<script src="~/assets/panel/js/pages/tables/jquery-datatable.js"></script>

Views/Fault/LastFaults.cshtml
@using teknikServisMVC.Models.Entities.Concrete;
@model ICollection<Ariza>;

<div class="col-lg-6 col-md-6 col-sm-6">
    <div class="card">
        <div class="header">
            <h2><strong>*En Son</strong> Arıza Kayıtları</h2>
        </div>
        <div class="body">
            <p>En son kaydedilen arıza kayıtları.</p>
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Müşteri</th>
                            <th>Cihaz Modeli</th>
                            <th>Açıklama</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (Model != null)
                        {
                            @foreach (var fault in Model)
                            {
                                <tr>
                                    <th scope="row">@fault.Id</th>
                                    <td>@fault.Musteri.Ad @fault.Musteri.Soyad </td>
                                    <td>@fault.Cihaz.Model</td>
                                    <td>@fault.Aciklama</td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

Views/Fault/LastUpdates.cshtml
@using teknikServisMVC.Models.Entities.Concrete;
@model ICollection<Ariza>;

<div class="col-lg-6 col-md-6 col-sm-6">
    <div class="card">
        <div class="header">
            <h2><strong>*En Son</strong> Yapılan işlemler</h2>  
        </div>
        <div class="body">
            <p>En son yapılan işlemler tablosu.</p>
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Müşteri</th>
                            <th>Marka</th>
                            <th>Cihaz Modeli</th>
                            <th>Durum</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (Model != null)
                        {
                            @foreach (var fault in Model)
                            {
                                <tr>
                                    <th scope="row">@fault.Id</th>
                                    <td>@fault.Musteri.Ad@fault.Musteri.Soyad</td>
                                    <td>@fault.Cihaz.Marka</td>
                                    <td>@fault.Cihaz.Model</td>
                                    <td>
                                        <span class="badge badge-info">@fault.ArizaDurumu.Ad</span>
                                    </td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

Views/Fault/ProcessFaults.cshtml
@{
    ViewData["Title"] = "İşlemdeki Arıza Kayıtları";
    Layout = "~/Views/Shared/PanelLayout.cshtml";
}
@model Tuple<object,List<object>,string>

<link rel="stylesheet" href="~/assets/panel/plugins/jquery-datatable/dataTables.bootstrap4.min.css">

<section class="content">
        <div class="body_scroll">
            <div class="block-header">
                <div class="row">
                    <div class="col-lg-7 col-md-6 col-sm-12">
                        <h2>İşlemdeki Arıza Kayıtları</h2>

                        <button class="btn btn-primary btn-icon mobile_menu" type="button"><i
                                class="zmdi zmdi-sort-amount-desc"></i></button>
                    </div>
                    <div class="col-lg-5 col-md-6 col-sm-12">
                        <button class="btn btn-primary btn-icon float-right right_icon_toggle_btn" type="button"><i
                                class="zmdi zmdi-arrow-right"></i></button>
                    </div>
                </div>
            </div>
            <div class="container-fluid">
                <div class="row clearfix">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="body">
                                <div class="table-responsive">
                                @await Component.InvokeAsync("DynamicTable",Model)
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
</section>


<!-- Jquery DataTable Plugin Js -->
<script src="~/assets/panel/bundles/datatablescripts.bundle.js"></script>
<script src="~/assets/panel/plugins/jquery-datatable/buttons/buttons.bootstrap4.min.js"></script>
<script src="~/assets/panel/plugins/jquery-datatable/buttons/buttons.colVis.min.js"></script>
<script src="~/assets/panel/plugins/jquery-datatable/buttons/buttons.flash.min.js"></script>
<script src="~/assets/panel/plugins/jquery-datatable/buttons/buttons.html5.min.js"></script>
<script src="~/assets/panel/plugins/jquery-datatable/buttons/buttons.print.min.js"></script>
<script src="~/assets/panel/js/pages/tables/jquery-datatable.js"></script>